@echo off
setlocal EnableDelayedExpansion

:: Configuration
set LOCAL_PORT=8081
set GITHUB_PAGES_DIR=github-pages\audiobookshelf

echo =====================================================
echo  Audiobookshelf Cloudflare Tunnel Launcher
echo =====================================================
echo.

:: Get script directory and project root
set SCRIPT_DIR=%~dp0
set PROJECT_ROOT=%SCRIPT_DIR%..

:: Check if cloudflared is installed
where cloudflared >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo ERROR: cloudflared is not installed or not in PATH.
    echo.
    echo Please install cloudflared:
    echo   winget install Cloudflare.cloudflared
    echo   OR
    echo   Download from: https://github.com/cloudflare/cloudflared/releases
    echo.
    pause
    exit /b 1
)

:: Check if git is installed
where git >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo ERROR: git is not installed or not in PATH.
    echo.
    pause
    exit /b 1
)

:: Verify github-pages directory exists
if not exist "%PROJECT_ROOT%\%GITHUB_PAGES_DIR%" (
    echo ERROR: GitHub Pages directory not found at:
    echo   %PROJECT_ROOT%\%GITHUB_PAGES_DIR%
    echo.
    echo Please ensure the github-pages/audiobookshelf folder exists.
    pause
    exit /b 1
)

:: Start cloudflared and capture output
echo Starting Cloudflare tunnel on port %LOCAL_PORT%...
echo.

:: Create a temporary file to capture the tunnel URL
set TUNNEL_LOG=%TEMP%\cloudflared_output.txt
del /q "%TUNNEL_LOG%" 2>nul

:: Start cloudflared in background
echo Waiting for tunnel URL...
start /b "" cmd /c "cloudflared tunnel --url http://localhost:%LOCAL_PORT% >> %TUNNEL_LOG% 2>&1"

:: Wait for tunnel to be established and extract URL
set TUNNEL_URL=
set RETRY_COUNT=0
set MAX_RETRIES=60

:wait_for_url
if %RETRY_COUNT% geq %MAX_RETRIES% (
    echo ERROR: Could not extract tunnel URL after %MAX_RETRIES% attempts.
    if exist "%TUNNEL_LOG%" (
        echo.
        echo Log file contents:
        type "%TUNNEL_LOG%"
    )
    pause
    exit /b 1
)

timeout /t 1 /nobreak >nul
set /a RETRY_COUNT+=1

:: Search for the tunnel URL in the log using PowerShell for more reliable parsing
for /f "delims=" %%u in ('powershell -NoProfile -Command "if (Test-Path '%TUNNEL_LOG%') { Select-String -Path '%TUNNEL_LOG%' -Pattern 'https://[a-z0-9-]+\.trycloudflare\.com' -AllMatches | ForEach-Object { $_.Matches.Value } | Select-Object -First 1 }"') do (
    set TUNNEL_URL=%%u
)

if "%TUNNEL_URL%"=="" goto wait_for_url

echo.
echo =====================================================
echo  Tunnel URL: %TUNNEL_URL%
echo =====================================================
echo.

:: Update config.js in the local github-pages directory
echo Updating config.js with new tunnel URL...
echo.

:: Auto-detect Wi-Fi LAN IP address
set LOCAL_URL=
set DETECTED_IP=
echo [INFO] Detecting local Wi-Fi IP address...
for /f "delims=" %%i in ('powershell -NoProfile -Command "$ip = Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -match 'Wi-Fi|WiFi|WLAN|Wireless' -and $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' } | Select-Object -First 1 -ExpandProperty IPAddress; if (-not $ip) { $ip = Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.PrefixOrigin -eq 'Dhcp' -and $_.IPAddress -notlike '127.*' } | Select-Object -First 1 -ExpandProperty IPAddress }; $ip"') do (
    set DETECTED_IP=%%i
)

if not "!DETECTED_IP!"=="" (
    set LOCAL_URL=http://!DETECTED_IP!:%LOCAL_PORT%
    echo [OK] Detected LAN IP: !LOCAL_URL!
) else (
    :: Fall back to existing localUrl from config.js
    for /f "delims=" %%u in ('powershell -NoProfile -Command "if (Test-Path '%PROJECT_ROOT%\%GITHUB_PAGES_DIR%\config.js') { $c = Get-Content '%PROJECT_ROOT%\%GITHUB_PAGES_DIR%\config.js' -Raw; if ($c -match 'localUrl:\s*''([^'']+)''') { $matches[1] } }"') do (
        set LOCAL_URL=%%u
    )
    if not "!LOCAL_URL!"=="" (
        echo [WARNING] Could not detect Wi-Fi IP. Keeping existing localUrl: !LOCAL_URL!
    ) else (
        echo [WARNING] Could not detect Wi-Fi IP. Set localUrl in config.js manually.
        echo [INFO] Example: http://192.168.1.100:%LOCAL_PORT%
    )
)

:: Get current timestamp using PowerShell for locale-independent format
for /f "delims=" %%a in ('powershell -NoProfile -Command "Get-Date -Format 'yyyy-MM-dd HH:mm:ss'"') do set TIMESTAMP=%%a

:: Update config.js
if "%LOCAL_URL%"=="" (
    (
    echo // Auto-generated by start-cloudflare-tunneling.bat
    echo // Do not edit manually - tunnelUrl is updated automatically when the tunnel starts
    echo // Set localUrl to your LAN backend address for LAN-first connection
    echo // Last updated: %TIMESTAMP%
    echo window.AUDIOBOOKSHELF_CONFIG = {
    echo   tunnelUrl: '%TUNNEL_URL%',
    echo   localUrl: '',
    echo   lastUpdated: '%TIMESTAMP%'
    echo };
    ) > "%PROJECT_ROOT%\%GITHUB_PAGES_DIR%\config.js"
) else (
    (
    echo // Auto-generated by start-cloudflare-tunneling.bat
    echo // Do not edit manually - tunnelUrl is updated automatically when the tunnel starts
    echo // Set localUrl to your LAN backend address for LAN-first connection
    echo // Last updated: %TIMESTAMP%
    echo window.AUDIOBOOKSHELF_CONFIG = {
    echo   tunnelUrl: '%TUNNEL_URL%',
    echo   localUrl: '!LOCAL_URL!',
    echo   lastUpdated: '%TIMESTAMP%'
    echo };
    ) > "%PROJECT_ROOT%\%GITHUB_PAGES_DIR%\config.js"
)

echo [OK] Updated config.js

:: Pull latest changes before committing
echo.
echo Pulling latest changes...
cd /d "%PROJECT_ROOT%"
git pull
if errorlevel 1 (
    echo [WARNING] Git pull failed. Continuing anyway...
)

:: Commit and push changes from project root
echo.
echo Committing and pushing changes...

echo [DEBUG] Running: git add "%GITHUB_PAGES_DIR%\config.js"
git add "%GITHUB_PAGES_DIR%\config.js"

echo [DEBUG] Running: git commit -m "Update tunnel URL - %TIMESTAMP%"
git commit -m "Update tunnel URL - %TIMESTAMP%"
if errorlevel 1 (
    echo [DEBUG] No changes to commit or commit failed
) else (
    echo [DEBUG] Git commit successful
    echo.
    echo Pushing to GitHub...
    echo [DEBUG] Running: git push
    git push
    if errorlevel 1 (
        echo WARNING: Could not push to GitHub. Check your credentials.
    ) else (
        echo.
        echo =====================================================
        echo  GitHub Pages will be updated via GitHub Actions!
        echo  Wait ~1 minute for deployment to complete.
        echo =====================================================
    )
)

:keep_running
echo.
echo =====================================================
echo  Tunnel is running. Press Ctrl+C to stop.
echo  Tunnel URL: %TUNNEL_URL%
echo =====================================================
echo.

:: Keep the script running
pause
exit /b 0
