@echo off
setlocal EnableDelayedExpansion

:: Configuration
set LOCAL_PORT=8081
set GITHUB_PAGES_DIR=github-pages\audiobookshelf

echo =====================================================
echo  Audiobookshelf Cloudflare Tunnel Launcher
echo =====================================================
echo.

:: Get script directory and project root
set SCRIPT_DIR=%~dp0
set PROJECT_ROOT=%SCRIPT_DIR%..

:: Check if cloudflared is installed
where cloudflared >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo ERROR: cloudflared is not installed or not in PATH.
    echo.
    echo Please install cloudflared:
    echo   winget install Cloudflare.cloudflared
    echo   OR
    echo   Download from: https://github.com/cloudflare/cloudflared/releases
    echo.
    pause
    exit /b 1
)

:: Check if git is installed
where git >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo ERROR: git is not installed or not in PATH.
    echo.
    pause
    exit /b 1
)

:: Verify github-pages directory exists
if not exist "%PROJECT_ROOT%\%GITHUB_PAGES_DIR%" (
    echo ERROR: GitHub Pages directory not found at:
    echo   %PROJECT_ROOT%\%GITHUB_PAGES_DIR%
    echo.
    echo Please ensure the github-pages/audiobookshelf folder exists.
    pause
    exit /b 1
)

:: Start cloudflared and capture output
echo Starting Cloudflare tunnel on port %LOCAL_PORT%...
echo.

:: Create a temporary file to capture the tunnel URL
set TUNNEL_LOG=%TEMP%\cloudflared_output.txt

:: Start cloudflared in background and redirect output
start /b cmd /c "cloudflared tunnel --url http://localhost:%LOCAL_PORT% 2>&1 | tee %TUNNEL_LOG%"

:: Wait for tunnel to be established and extract URL
echo Waiting for tunnel URL...
set TUNNEL_URL=
set RETRY_COUNT=0
set MAX_RETRIES=30

:wait_for_url
if %RETRY_COUNT% geq %MAX_RETRIES% (
    echo ERROR: Could not extract tunnel URL after %MAX_RETRIES% attempts.
    echo Check %TUNNEL_LOG% for details.
    pause
    exit /b 1
)

timeout /t 2 /nobreak >nul
set /a RETRY_COUNT+=1

:: Search for the tunnel URL in the log
for /f "tokens=*" %%a in ('findstr /r /c:"https://.*\.trycloudflare\.com" %TUNNEL_LOG% 2^>nul') do (
    for /f "tokens=2 delims= " %%u in ("%%a") do (
        set TUNNEL_URL=%%u
    )
)

:: Also try alternative pattern
if "%TUNNEL_URL%"=="" (
    for /f "tokens=*" %%a in ('findstr /c:"trycloudflare.com" %TUNNEL_LOG% 2^>nul') do (
        echo %%a | findstr /r "https://[a-z0-9-]*\.trycloudflare\.com" >nul
        if !ERRORLEVEL! equ 0 (
            for /f "delims=" %%u in ('echo %%a ^| powershell -Command "$input | Select-String -Pattern 'https://[a-z0-9-]+\.trycloudflare\.com' -AllMatches | ForEach-Object { $_.Matches.Value }"') do (
                set TUNNEL_URL=%%u
            )
        )
    )
)

if "%TUNNEL_URL%"=="" goto wait_for_url

:: Clean up the URL (remove any trailing characters)
for /f "tokens=1" %%u in ("%TUNNEL_URL%") do set TUNNEL_URL=%%u

echo.
echo =====================================================
echo  Tunnel URL: %TUNNEL_URL%
echo =====================================================
echo.

:: Update config.js in the local github-pages directory
echo Updating config.js with new tunnel URL...
echo.

:: Get current timestamp
for /f "tokens=1-3 delims=/ " %%a in ('echo %date%') do set DATE_STR=%%c-%%a-%%b
for /f "tokens=1-3 delims=:." %%a in ('echo %time%') do set TIME_STR=%%a:%%b:%%c
set TIMESTAMP=%DATE_STR% %TIME_STR%

:: Update config.js
(
echo // Auto-generated by start-cloudflare-tunneling.bat
echo // Do not edit manually - this file is updated automatically when the tunnel starts
echo // Last updated: %TIMESTAMP%
echo window.AUDIOBOOKSHELF_CONFIG = {
echo   tunnelUrl: '%TUNNEL_URL%',
echo   lastUpdated: '%TIMESTAMP%'
echo };
) > "%PROJECT_ROOT%\%GITHUB_PAGES_DIR%\config.js"

echo [OK] Updated config.js

:: Commit and push changes from project root
echo.
echo Committing and pushing changes...
cd /d "%PROJECT_ROOT%"

git add "%GITHUB_PAGES_DIR%\config.js"
git commit -m "Update tunnel URL - %TIMESTAMP%" 2>nul
if %ERRORLEVEL% equ 0 (
    echo Pushing to GitHub...
    git push 2>nul
    if %ERRORLEVEL% equ 0 (
        echo.
        echo =====================================================
        echo  GitHub Pages will be updated via GitHub Actions!
        echo  Wait ~1 minute for deployment to complete.
        echo =====================================================
    ) else (
        echo WARNING: Could not push to GitHub. Check your credentials.
    )
) else (
    echo No changes to commit (URL may be the same).
)

:keep_running
echo.
echo =====================================================
echo  Tunnel is running. Press Ctrl+C to stop.
echo  Tunnel URL: %TUNNEL_URL%
echo =====================================================
echo.

:: Keep the script running
pause
goto :eof
