// Auto-generated by start-cloudflare-tunneling.bat
// Do not edit manually - this file is updated automatically when the tunnel starts
// Last updated: 24-2026-01 17:35:18
window.AUDIOBOOKSHELF_CONFIG = {
  tunnelUrl: 'INF',
  lastUpdated: '24-2026-01 17:35:18'
};
