// Auto-generated by start-cloudflare-tunneling.bat
// Do not edit manually - this file is updated automatically when the tunnel starts
// Last updated: 2026-01-24 17:37:44
window.AUDIOBOOKSHELF_CONFIG = {
  tunnelUrl: 'https://integrating-july-execute-participate.trycloudflare.com',
  lastUpdated: '2026-01-24 17:37:44'
};
