// Auto-generated by start-cloudflare-tunneling.bat
// Do not edit manually - this file is updated automatically when the tunnel starts
// Last updated: 24-2026-01 17:36:17
window.AUDIOBOOKSHELF_CONFIG = {
  tunnelUrl: 'https://ultimately-infectious-option-themes.trycloudflare.com',
  lastUpdated: '24-2026-01 17:36:17'
};
